/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/clients/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search clients */
        get: operations["clientssearch_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/{client_id}/diagnoses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get client's diagnoses */
        get: operations["clients__int_client_id__diagnoses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients_signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search clients */
        get: operations["clients_signup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search for existing appointments */
        get: operations["appointments_get"];
        put?: never;
        /** Create a new appointment */
        post: operations["appointments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appointments/{appointment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an existing appointment */
        get: operations["appointments__int_appointment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appointments/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete all appointments by therapist email from db */
        delete: operations["appointmentsall_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/therapists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get therapists table */
        get: operations["therapists_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/therapists/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Match client with therapists */
        get: operations["therapists_match_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/therapists/calendar_events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get calendar events */
        get: operations["therapists_calendar_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/therapists/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the media link */
        get: operations["therapists_media_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/therapists/with_calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get therapists who shared their calendar */
        get: operations["therapistswith_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/therapists/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get therapist's available slots by calendar email */
        get: operations["therapistsslots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/therapist_videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all therapist's videos */
        get: operations["therapist_videos_get"];
        put?: never;
        /** Set therapist's videos */
        post: operations["therapist_videos_post"];
        delete?: never;
        options?: never;
        head?: never;
        /** Update therapist's video */
        patch: operations["therapist_videos_patch"];
        trace?: never;
    };
    "/intakeq_forms/mandatory_form": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send mandatory form and get its link */
        post: operations["intakeq_formsmandatory_form_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Webhook for typeform */
        post: operations["typeform_webhook_hook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intakeq_hook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Webhook for IntakeQ Appointments */
        post: operations["intakeq_hook_intakeq_hook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Clients */
        Clients: {
            /** Clients */
            clients?: components["schemas"]["Client"][];
        };
        /** CustomField */
        CustomField: {
            /** Fieldid */
            FieldId?: string;
            /** Value */
            Value?: string;
            /** Text */
            Text?: string;
        };
        /** Client */
        Client: {
            /** Clientid */
            ClientId?: string;
            /** Firstname */
            FirstName?: string;
            /** Lastname */
            LastName?: string;
            /** Middlename */
            MiddleName?: string;
            /** Name */
            Name?: string;
            /** Email */
            Email?: string;
            /** Phone */
            Phone?: string;
            /** Gender */
            Gender?: string;
            /** Stateshort */
            StateShort?: string;
            /** Dateofbirth */
            DateOfBirth?: number;
            /**
             * Country
             * @default US
             */
            Country: string;
            /** Additionalinformation */
            AdditionalInformation?: string;
            /** Customfields */
            CustomFields?: components["schemas"]["CustomField"][];
            /** Guid */
            Guid?: string;
            /** Mobilephone */
            MobilePhone?: number;
            /** Archived */
            Archived?: boolean;
            /** Tags */
            Tags?: string[];
            /** Practitionerid */
            PractitionerId?: string;
            /** Linkedclients */
            LinkedClients?: string[];
            /** Datecreated */
            DateCreated?: number;
            /** Billingtype */
            BillingType?: number;
            /** Lastactivityname */
            LastActivityName?: string;
            /** Creditbalance */
            CreditBalance?: number;
            /** Lastactivitydate */
            LastActivityDate?: number;
            /** Lastupdatedate */
            LastUpdateDate?: number;
        };
        /** ClientDiagnoses */
        ClientDiagnoses: {
            /** Diagnoses */
            diagnoses?: components["schemas"]["ClientDiagnose"][];
        };
        /** ClientDiagnose */
        ClientDiagnose: {
            /** Code */
            Code?: string;
            /** Description */
            Description?: string;
            /** Date */
            Date?: string;
            /** Enddate */
            EndDate?: string;
            /** Noteid */
            NoteId?: string;
        };
        /** ClientSignup */
        ClientSignup: {
            /**
             * Id
             * Format: uuid4
             */
            id: string;
            /** Response Id */
            response_id?: string;
            /** First Name */
            first_name?: string;
            /** Last Name */
            last_name?: string;
            /** Email */
            email?: string;
            /** Phone */
            phone?: string;
            /** Gender */
            gender?: string;
            /** Age */
            age?: string;
            /** State */
            state?: string;
            /** I Would Like Therapist */
            i_would_like_therapist?: string[];
            /** Alcohol */
            alcohol?: string;
            /** Drugs */
            drugs?: string;
            /** Pleasure Doing Things */
            pleasure_doing_things?: string;
            /** Feeling Down */
            feeling_down?: string;
            /** Trouble Falling */
            trouble_falling?: string;
            /** Feeling Tired */
            feeling_tired?: string;
            /** Poor Appetite */
            poor_appetite?: string;
            /** Feeling Bad About Yourself */
            feeling_bad_about_yourself?: string;
            /** Trouble Concentrating */
            trouble_concentrating?: string;
            /** Moving Or Speaking So Slowly */
            moving_or_speaking_so_slowly?: string;
            /** Suicidal Thoughts */
            suicidal_thoughts?: string;
            /** Feeling Nervous */
            feeling_nervous?: string;
            /** Not Control Worrying */
            not_control_worrying?: string;
            /** Worrying Too Much */
            worrying_too_much?: string;
            /** Trouble Relaxing */
            trouble_relaxing?: string;
            /** Being So Restless */
            being_so_restless?: string;
            /** Easily Annoyed */
            easily_annoyed?: string;
            /** Feeling Afraid */
            feeling_afraid?: string;
            /** University */
            university?: string;
            /** What Brings You */
            what_brings_you?: string;
            /** Lived Experiences */
            lived_experiences?: string[];
            /** Best Time For First Session */
            best_time_for_first_session?: string;
            /** Promo Code */
            promo_code?: string;
            /** Referred By */
            referred_by?: string;
        };
        /** Error */
        Error: {
            /** Error */
            error: string;
        };
        /** Appointments */
        Appointments: {
            /** Appointments */
            appointments?: components["schemas"]["Appointment"][];
        };
        /** AdditionalClient */
        AdditionalClient: {
            /** Clientid */
            ClientId?: string;
            /** Clientname */
            ClientName?: string;
            /** Clientemail */
            ClientEmail?: string;
            /** Clientphone */
            ClientPhone?: string;
            /** Intakeid */
            IntakeId?: string;
        };
        /** Appointment */
        Appointment: {
            /** Enddatelocal */
            EndDateLocal?: string;
            /** Datecreated */
            DateCreated?: number;
            /** Locationname */
            LocationName?: string;
            /** Startdate */
            StartDate?: number;
            /** Lastmodified */
            LastModified?: number;
            /** Fullcancellationreason */
            FullCancellationReason?: string;
            /** Clientname */
            ClientName?: string;
            /** Enddateiso */
            EndDateIso?: string;
            /** Startdatelocalformatted */
            StartDateLocalFormatted?: string;
            /** Clientid */
            ClientId?: string;
            /** Startdateiso */
            StartDateIso: string;
            /** Practitionername */
            PractitionerName?: string;
            /** Remindertype */
            ReminderType?: string;
            /** Status */
            Status?: string;
            /** Createdby */
            CreatedBy?: string;
            /** Cancellationdate */
            CancellationDate?: string;
            /** Locationid */
            LocationId?: string;
            /** Duration */
            Duration?: number;
            /** Practitionerid */
            PractitionerId?: string;
            /** Clientemail */
            ClientEmail?: string;
            /** Enddate */
            EndDate?: number;
            /** Bookedbyclient */
            BookedByClient?: boolean;
            /** Additionalclients */
            AdditionalClients?: components["schemas"]["AdditionalClient"][];
            /** Customfields */
            CustomFields?: components["schemas"]["CustomField"][];
            /** Price */
            Price?: number;
            /** Attendanceconfirmationresponse */
            AttendanceConfirmationResponse?: string;
            /** Id */
            Id?: string;
            /** Practitioneremail */
            PractitionerEmail?: string;
            /** Startdatelocal */
            StartDateLocal?: string;
        };
        /** CreateAppointment */
        CreateAppointment: {
            /** Client Response Id */
            client_response_id: string;
            /** Therapist Email */
            therapist_email: string;
            /** Datetime */
            datetime: string;
            /** Send Client Email Notification */
            send_client_email_notification: boolean;
            /** Reminder Type */
            reminder_type?: string;
            /** Status */
            status: string;
        };
        /** Therapists */
        Therapists: {
            /** Therapists */
            therapists: components["schemas"]["Therapist"][];
        };
        /** Therapist */
        Therapist: {
            /** Available Slots */
            available_slots?: string[];
            /** Id */
            id: string;
            /** Intern Name */
            intern_name?: string;
            /** Age */
            age?: string;
            /** Email */
            email?: string;
            /** Calendar Email */
            calendar_email?: string;
            /** Biography */
            biography?: string;
            /** Availability */
            availability?: string[];
            /** Birth Order */
            birth_order?: string;
            /** Caretaker Role */
            caretaker_role?: boolean;
            /** Caseload Tracker */
            caseload_tracker?: string;
            /** Has Children */
            has_children?: boolean;
            /** Cohort */
            cohort?: string;
            /** Diagnoses */
            diagnoses?: string[];
            /** Ethnicity */
            ethnicity?: string[];
            /** Gender */
            gender?: string;
            /** Identities As */
            identities_as?: string;
            /** Gender Interest */
            gender_interest?: string;
            /** Immigration Background */
            immigration_background?: string;
            /** Lgbtq Part */
            lgbtq_part?: boolean;
            /** Culture */
            culture?: string;
            /** Places */
            places?: string;
            /** Married */
            married?: boolean;
            /** Max Caseload */
            max_caseload?: string;
            /** Neurodivergence */
            neurodivergence?: string;
            /** Performing */
            performing?: boolean;
            /** Program */
            program?: string;
            /** Religion */
            religion?: string[];
            /** Experience With Risk Clients */
            experience_with_risk_clients?: string;
            /** Working With Lgbtq Clients */
            working_with_lgbtq_clients?: string;
            /** Negative Affect By Social Media */
            negative_affect_by_social_media?: boolean;
            /** Specialities */
            specialities?: string[];
            /** States */
            states?: string[];
            /** Therapeutic Orientation */
            therapeutic_orientation?: string[];
            /** Family Household */
            family_household?: string;
            /** Welcome Video Link */
            welcome_video_link?: string;
            /** Greetings Video Link */
            greetings_video_link?: string;
            /** Image Link */
            image_link?: string;
        };
        /** MatchedTherapists */
        MatchedTherapists: {
            client?: components["schemas"]["ClientShort"];
            /** Therapists */
            therapists?: components["schemas"]["ClientMatch"][];
        };
        /** ClientShort */
        ClientShort: {
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** First Name */
            first_name?: string;
            /** Last Name */
            last_name?: string;
            /** Email */
            email?: string;
            /** Response Id */
            response_id?: string;
        };
        /** ClientMatch */
        ClientMatch: {
            therapist: components["schemas"]["Therapist"];
            /** Score */
            score: number;
            /** Matched Diagnoses */
            matched_diagnoses: string[];
            /** Matched Specialities */
            matched_specialities: string[];
        };
        /** CalendarEvents */
        CalendarEvents: {
            /** Data */
            data?: components["schemas"]["CalendarEventsDateGroup"][];
        };
        /** CalendarEvent */
        CalendarEvent: {
            /** Start */
            start?: string;
            /** End */
            end?: string;
            /** Event */
            event?: string;
            /** Description */
            description?: string;
            /** Recurrence */
            recurrence?: string[];
        };
        /** CalendarEventsDateGroup */
        CalendarEventsDateGroup: {
            /** Date */
            date: string;
            /** Events */
            events: components["schemas"]["CalendarEvent"][];
        };
        /**
         * S3MediaType
         * @description An enumeration.
         * @enum {unknown}
         */
        S3MediaType: "image" | "welcome_video" | "intro_video";
        /** MediaLink */
        MediaLink: {
            /** Url */
            url: string;
        };
        /** TherapistEmails */
        TherapistEmails: {
            /** Emails */
            emails: string[];
        };
        /** AvailableSlots */
        AvailableSlots: {
            /** Available Slots */
            available_slots?: string[];
        };
        /** TherapistVideos */
        TherapistVideos: {
            /** Videos */
            videos: components["schemas"]["TherapistVideo"][];
        };
        /**
         * VideoType
         * @description An enumeration.
         * @enum {unknown}
         */
        VideoType: "welcome" | "greeting";
        /** TherapistVideo */
        TherapistVideo: {
            /** Name */
            name?: string;
            /** Email */
            email?: string;
            /** Video Url */
            video_url: string;
            type: components["schemas"]["VideoType"];
        };
        /** IntakeQMandatoryFormQuery */
        IntakeQMandatoryFormQuery: {
            /** Client Id */
            client_id: string;
            /** Therapist Id */
            therapist_id: string;
        };
        /** Url */
        Url: {
            /** Url */
            url: string;
        };
        /** SuccessResponse */
        SuccessResponse: {
            /** Success */
            success: boolean;
        };
        /** ValidationErrorModel */
        ValidationErrorModel: {
            /**
             * Location
             * @description the error's location as a list.
             */
            loc?: string[];
            /**
             * Message
             * @description a computer-readable identifier of the error type.
             */
            msg?: string;
            /**
             * Error Type
             * @description a human readable explanation of the error.
             */
            type_?: string;
            /**
             * Error context
             * @description an optional object which contains values required to render the error message.
             */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    clientssearch_get: {
        parameters: {
            query?: {
                search?: string;
                page?: string;
                dateCreatedStar?: string;
                dateCreatedEnd?: string;
                dateUpdatedStart?: string;
                dateUpdatedEnd?: string;
                externalClientId?: string;
                deletedOnly?: boolean;
                IncludeProfile?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Clients"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorModel"][];
                };
            };
        };
    };
    clients__int_client_id__diagnoses_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientDiagnoses"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorModel"][];
                };
            };
        };
    };
    clients_signup_get: {
        parameters: {
            query: {
                response_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientSignup"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorModel"][];
                };
            };
        };
    };
    appointments_get: {
        parameters: {
            query?: {
                client?: number;
                startDate?: string;
                endDate?: string;
                status?: string;
                practitionerEmail?: string;
                page?: number;
                updatedSince?: string;
                deletedOnly?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Appointments"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorModel"][];
                };
            };
        };
    };
    appointments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAppointment"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Appointment"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorModel"][];
                };
            };
        };
    };
    appointments__int_appointment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appointment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Appointment"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorModel"][];
                };
            };
        };
    };
    appointmentsall_delete: {
        parameters: {
            query: {
                email: string;
                admin_password: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorModel"][];
                };
            };
        };
    };
    therapists_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Therapists"];
                };
            };
        };
    };
    therapists_match_get: {
        parameters: {
            query: {
                limit?: number;
                last_index?: number;
                /** @example Client response id */
                response_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchedTherapists"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorModel"][];
                };
            };
        };
    };
    therapists_calendar_events_get: {
        parameters: {
            query: {
                calendar_id: string;
                date_min?: string;
                date_max?: string;
                max_results?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarEvents"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorModel"][];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    therapists_media_get: {
        parameters: {
            query: {
                email: string;
                type: components["schemas"]["S3MediaType"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaLink"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorModel"][];
                };
            };
        };
    };
    therapistswith_calendar_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TherapistEmails"];
                };
            };
        };
    };
    therapistsslots_get: {
        parameters: {
            query: {
                email: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailableSlots"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorModel"][];
                };
            };
        };
    };
    therapist_videos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TherapistVideos"];
                };
            };
        };
    };
    therapist_videos_post: {
        parameters: {
            query: {
                admin_password: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TherapistVideos"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TherapistVideos"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorModel"][];
                };
            };
        };
    };
    therapist_videos_patch: {
        parameters: {
            query: {
                admin_password: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TherapistVideo"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TherapistVideo"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorModel"][];
                };
            };
        };
    };
    intakeq_formsmandatory_form_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntakeQMandatoryFormQuery"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Url"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorModel"][];
                };
            };
        };
    };
    typeform_webhook_hook_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
        };
    };
    intakeq_hook_intakeq_hook_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
}
