export enum STEPS {
  TYPEFORM = 'TYPEFORM',
  TYPEFORM_WAIT_LIST = 'TYPEFORM_WAIT_LIST',
  MATCHED_THERAPIST = 'MATCHED_THERAPIST',
  CONFIRMATION = 'CONFIRMATION',
  NO_MATCH = 'NO_MATCH',
}

export const CALENDAR_WEEK_DAYS = ['s', 'm', 't', 'w', 't', 'f', 's'];

export const CALENDAR_GROUP_DATE_FORMAT = 'yyyy-MM-dd';
